name: chkoba_app
description: Tunisian card games - local WiFi hotspot multiplayer. Starting with Chkoba.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  shelf: ^1.4.1
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^2.4.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
